<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eSubpackages name="xmlUI" nsPrefix="xmlUI">
    <eClassifiers xsi:type="ecore:EClass" name="XMLPage">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="panels" upperBound="-1"
          eType="#//xmlUI/XMLPanel" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XMLPanel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="validType" value="self.type = &quot;StackPanel&quot; or self.type = &quot;Grid&quot;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="buttons" ordered="false"
          upperBound="-1" eType="#//xmlUI/XMLButton" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="comboBoxes" upperBound="-1"
          eType="#//xmlUI/XMLComboBox" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="textBlocks" upperBound="-1"
          eType="#//xmlUI/XMLTextBlock" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XMLButton">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XMLComboBox">
      <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="2"
          upperBound="-1" eType="#//xmlUI/Item"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="selectedItem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XMLTextBlock">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Item">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
