<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="XMLUI" nsURI="http://TACS" nsPrefix="XMLUI">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="XMLPage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="validHeight validWidth"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="validHeight" value="&#xA;&#x9;&#x9;&#x9;self.height >= 50 and self.height &lt;= 3000"/>
      <details key="validWidth" value="&#xA;&#x9;&#x9;&#x9;self.width >= 50 and self.width &lt;= 3000"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="panels" upperBound="-1"
        eType="#//XMLPanel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLPanel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueButtonContent uniqueButtonCommand noSelfContainment"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueButtonContent" value="&#xA;&#x9;&#x9;&#x9;self.buttons->forAll(b1, b2 | b1 &lt;> b2 implies b1.content &lt;> b2.content)"/>
      <details key="uniqueButtonCommand" value="&#xA;&#x9;&#x9;&#x9;self.buttons->forAll(b1, b2 | b1 &lt;> b2 implies b1.command &lt;> b2.command)"/>
      <details key="noSelfContainment" value="&#xA;            not self.panels->closure(p | p.panels)->exists(c | c.id = self.id)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//panelType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buttons" upperBound="-1"
        eType="#//XMLButton" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comboBoxes" upperBound="-1"
        eType="#//XMLComboBox" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textBlocks" upperBound="-1"
        eType="#//XMLTextBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="panels" upperBound="-1"
        eType="#//XMLPanel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLButton">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLComboBox">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="selectedItemMustBeInItems"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="selectedItemMustBeInItems" value="&#xA;&#x9;&#x9;&#x9;self.items->exists(item | item.text = self.selectedItem)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selectedItem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="2" upperBound="-1"
        eType="#//Item" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLTextBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="panelType">
    <eLiterals name="StackPanel"/>
    <eLiterals name="Grid" value="1"/>
  </eClassifiers>
</ecore:EPackage>
